/**
 * This module ought to be used to add factory functions for data used in jest
 * unit/integration tests.
 *
 * The general idea is, a factory function accepts a Partial version of the type
 * it creates, where the partial version can contain all the properties the
 * original type contains, but all of them are optional.
 *
 * The factory function then sets default values for properties not provided.
 */

export * from './buildAdminTeamPayload'
export * from './buildAnnotation'
export * from './buildAnnotationActorPayload'
export * from './buildAnnotationClassPayload'
export * from './buildAnnotationCreditPayload'
export * from './buildAnnotationPayload'
export * from './buildAnnotationTypePayload'
export * from './buildApiKeyPayload'
export * from './buildAttributePayload'
export * from './buildAxiosResponse'
export * from './buildBillingInfoPayload'
export * from './buildBillingInfoSelectedSource'
export * from './buildBoundingBoxVideoAnnotation'
export * from './buildClassUsagePayload'
export * from './buildClientTeamInvitationPayload'
export * from './buildComment'
export * from './buildCommentPayload'
export * from './buildCommentThread'
export * from './buildCommentThreadPayload'
export * from './buildCountry'
export * from './buildCreditUsagePayload'
export * from './buildCustomerPayload'
export * from './buildCustomerSubscriptionPayload'
export * from './buildDatasetAnnotationReportPayload'
export * from './buildDatasetAnnotatorPayload'
export * from './buildDatasetDetailPayload'
export * from './buildDatasetDicomPayload'
export * from './buildDatasetExportPayload'
export * from './buildDatasetFolderPayload'
export * from './buildDatasetImagePayload'
export * from './buildDatasetItemFilenamePayload'
export * from './buildDatasetItemFilter'
export * from './buildDatasetItemPayload'
export * from './buildDatasetItemReportPayload'
export * from './buildDatasetItemsCountPayload'
export * from './buildDatasetItemTimeSummaryPayload'
export * from './buildDatasetPayload'
export * from './buildDatasetReportPayload'
export * from './buildDatasetVideoPayload'
export * from './buildErrorWithMessage'
export * from './buildFeaturePayload'
export * from './buildImageData'
export * from './buildImagePayload'
export * from './buildInferenceRequestCountPayload'
export * from './buildInstanceCountPayload'
export * from './buildInvitationPayload'
export * from './buildInvoicePayload'
export * from './buildLoadedFrame'
export * from './buildLoadedImage'
export * from './buildLoadedVideo'
export * from './buildLocation'
export * from './buildLogin2faResponsePayload'
export * from './buildLoginResponsePayload'
export * from './buildMeasureRegionsPayload'
export * from './buildMembershipPayload'
export * from './buildMetricPayload'
export * from './buildModelPayload'
export * from './buildModelTemplatePayload'
export * from './buildNotificationPayload'
export * from './buildParsedError'
export * from './buildPresetPayload'
export * from './buildRenderableImage'
export * from './buildRoute'
export * from './buildRunningSessionInstanceCountPayload'
export * from './buildRunningSessionPayload'
export * from './buildSkeletonEdgeType'
export * from './buildSkeletonNodeType'
export * from './buildStageAnnotation'
export * from './buildStageAnnotationPayload'
export * from './buildTeamOwnerInvitationPayload'
export * from './buildTeamPayload'
export * from './buildTeamUploadInfoPayload'
export * from './buildToolConfigEntry'
export * from './buildTrainedModelPayload'
export * from './buildTrainingClass'
export * from './buildTrainingSessionPayload'
export * from './buildUploadImage'
export * from './buildUploadOtherFile'
export * from './buildUploadVideo'
export * from './buildUsageReportPayload'
export * from './buildUserPayload'
export * from './buildVideoFramePayload'
export * from './buildWorkflowPayload'
export * from './buildWorkflowActionPayload'
export * from './buildWorkflowStagePayload'
export * from './buildWorkflowStageTemplatePayload'
export * from './buildWorkflowTemplatePayload'
export * from './buildWorkforceManagerPayload'
export * from './createFile'

// 2.0
export * from './buildV2Annotation'
export * from './buildV2CommentPayload'
export * from './buildV2CommentThreadPayload'
export * from './buildV2DatasetFolderPayload'
export * from './buildV2DatasetItemFilter'
export * from './buildV2DatasetItemPayload'
export * from './buildV2DatasetItemTimeSummaryPayload'
export * from './buildV2WorkflowItemPayload'
export * from './buildV2WorkflowItemStatePayload'
export * from './buildV2WorkflowPayload'
export * from './buildV2WorkflowStageInstancePayload'
export * from './buildV2WorkflowStagePayload'
