export { default as IconColoredAnnotate } from './annotate-stage.svg?inline'
export { default as IconColoredCode } from './code-stage.svg?inline'
export { default as IconColoredComplete } from './complete-stage.svg?inline'
export { default as IconColoredConsensus } from './consensus-stage.svg?inline'
export { default as IconColoredDataset } from './dataset-stage.svg?inline'
export { default as IconColoredLogic } from './logic-stage.svg?inline'
export { default as IconColoredModel } from './model-stage.svg?inline'
export { default as IconColoredReview } from './review-stage.svg?inline'
export { default as IconColoredTest } from './test-stage.svg?inline'
export { default as IconColoredWebhook } from './webhook-stage.svg?inline'

export { default as IconColoredAnnotateInverted } from './annotate-stage-inverted.svg?inline'
export { default as IconColoredCodeInverted } from './code-stage-inverted.svg?inline'
export { default as IconColoredCompleteInverted } from './complete-stage-inverted.svg?inline'
export { default as IconColoredConsensusInverted } from './consensus-stage-inverted.svg?inline'
export { default as IconColoredDatasetInverted } from './dataset-stage-inverted.svg?inline'
export { default as IconColoredModelInverted } from './model-stage-inverted.svg?inline'
export { default as IconColoredReviewInverted } from './review-stage-inverted.svg?inline'
export { default as IconColoredTestInverted } from './test-stage-inverted.svg?inline'
export { default as IconColoredWebhookInverted } from './webhook-stage-inverted.svg?inline'

export { default as IconColoredReject } from './reject.svg?inline'
export { default as IconColoredRejectInverted } from './reject-inverted.svg?inline'

export { default as IconColoredBoundingBoxPink } from './bounding-box-pink.svg?inline'
export { default as IconColoredPolygonCyan } from './polygon-cyan.svg?inline'
export { default as IconColoredSum } from './sum.svg?inline'
