/**
 * Represents a comment conversation made in a workview.
 *
 * A conversation starts by drawing a bounding box on top of an item slot,
 * followed by typing out the comment itself.
 *
 * This creates the thread with a single comment
 *
 * Once there, other users can post replies to the same thread which adds
 * additional comments to it.
 *
 * The comment thread author can eventually resolve the thread, which will make
 * it no longer be listed.
 *
 * If the thread is created on a simple item, it will be associated to the item
 * and the single slot of the item.
 *
 * If it's a multi slot item, it will be associated to the item and one of the
 * item slots.
 *
 * If it's a video, it will additionally be associated to a frame of the video.
 */
export type CommentThread = {
  /* eslint-disable camelcase */
  /**
   * User id of the user who created the comment thread
   */
  author_id: number
  /**
   * Position of the comment thread on top of a slot in an item
   */
  bounding_box: { x: number; y: number; w: number; h: number }
  /**
   * Total number of comments the thread contains
   */
  comment_count: number
  /**
   * Types of issues that caused the thread to be created by system user
   */
  issue_types: string[] | null
  /**
   * Data describing which annotations didn't satisfy the IoU threshold
   */
  issue_data: IssueDataPayload | null
  /**
   * Id of the 2.0 dataset item the thread is created for
   */
  dataset_item_id: string
  /**
   * UUID of the thread itself
   */
  id: string
  /**
   * Timestamp of then the thread was first created
   */
  inserted_at: string
  /**
   * Flag indicating whether the comment thread is resolved.
   * Once resolved, the thread will no longer be sent by the backend.
   */
  resolved: boolean
  /**
   * Index of the section of a multi-section slot
   */
  section_index: number | null
  /**
   * Name of the slot the thread relates to
   */
  slot_name: string
  /**
   * Timestamp of the last moment the thread was updated.
   * Updating a comment belonging to the thread does NOT update this timestamp.
   */
  updated_at: string
  /* eslint-enable camelcase */
}

type IssueDataPayload = {
  annotation_ids: string[]
  disagreement: {
    ious: [
      {
        champion_annotation_id: string
        other_annotation_id: string
        // 0 to 1
        iou: number
      }
    ] | null
  } | null
}

/**
 * Represents a reply to a comment thread, or the original comment of the thread.
 * A thread with no replies will have just the 1 original comment.
 * A thread with replies will have 2 or more comments.
 */
export type Comment = {
  /* eslint-disable camelcase */
  /**
   * User id of the thread author
   */
  author_id: number
  /**
   * Actual comment body
   */
  body: string
  /** temporary field indicating if the comment is generated by the system */
  created_by_system?: boolean
  /**
   * UUID of the parent comment thread
   */
  comment_thread_id: string
  /**
   * UUID of the comment itself
   */
  id: string
  /**
   * ISO timestamp of when the comment was created.
   * The comments should be sorted by this to be listed in correct order.
   */
  inserted_at: string
  /**
   * ISO timestamp of when the comment was last edited.
   * Same as `inserted_at` if it was not edited.
   */
  updated_at: string
  /* eslint-enable camelcase */
}

export interface Provider { }

/**
 * Provides an interface to perform CRUD operations on comments
 */
export interface ICommentsProvider extends Provider {
  getThreads(): Promise<CommentThread[]>
  createThread(
    payload: CommentThread,
    initialComment: string
  ): Promise<CommentThread>
  updateThread(payload: CommentThread): Promise<CommentThread>
  removeThread(payload: CommentThread): Promise<void>
  unreadThread(payload: CommentThread): Promise<void>
  resolveThread(payload: CommentThread): Promise<CommentThread>

  getComments(thread: CommentThread): Promise<Comment[]>
  createComment (
    body: string,
    thread: CommentThread
  ): Promise<Comment>
  updateComment(
    comment: Comment,
    thread: CommentThread
  ): Promise<Comment>
  removeComment (comment: Comment, thread: CommentThread): Promise<void>
}

export type Providers = {
  commentsProvider: ICommentsProvider
}
